### ISSUE TITLE
域名解析失败了

### ISSUE THREAD

**Issue by wangwanjie** [niebinxiao/ddns-centos#1]
2023-06-03 12:45:32.210 [main] ERROR cloud.tools.aliyun.sdk.ddns.DDNS - 域名解析失败
com.aliyuncs.exceptions.ClientException: InvalidParameter : The parameter value Value is invalid.
RequestId : 4726A486-B329-53B7-B3E8-7EEFA443C3CC
        at com.aliyuncs.DefaultAcsClient.parseAcsResponse(DefaultAcsClient.java:218)
        at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:115)
        at cloud.tools.aliyun.sdk.ddns.DDNS.main(DDNS.java:51)

**Comment by niebinxiao** [comment]
这咋排查？
